spring:
  application:
    name: justificativo-microservice
  datasource:
    url:
      jdbc:mysql://localhost:3306/mtisw2_justificativos
    password: danielusach
    username: root
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8083
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


